// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	unstableInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(unstableInfo) })
}

func (r unstableInfo) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	if err := r.Encode(buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r unstableInfo) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeSimple(buf, r.ContainsPlatformPrivateApis); err != nil {
		return err
	}
	return err
}

func (r *unstableInfo) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	return r.Decode(buf)
}

func (r *unstableInfo) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeSimple[bool](buf, &r.ContainsPlatformPrivateApis)
	if err != nil {
		return err
	}

	return err
}

var unstableInfoGobRegId int16

func (r unstableInfo) GetTypeId() int16 {
	return unstableInfoGobRegId
}
