// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func (r katiInstall) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	var err error

	if err = gobtools.EncodeStruct(buf, &r.from); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeStruct(buf, &r.to); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeStruct(buf, &r.implicitDeps); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeStruct(buf, &r.orderOnlyDeps); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, r.executable); err != nil {
		return nil, err
	}

	isNil6 := r.extraFiles == nil
	if err = gobtools.EncodeSimple(buf, isNil6); err != nil {
		return nil, err
	}
	if !isNil6 {
		if err = gobtools.EncodeStruct(buf, &*r.extraFiles); err != nil {
			return nil, err
		}
	}

	if err = gobtools.EncodeString(buf, r.absFrom); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r *katiInstall) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	err := r.Decode(buf)
	return err
}

func (r *katiInstall) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeStruct(buf, &r.from)
	if err != nil {
		return err
	}

	err = gobtools.DecodeStruct(buf, &r.to)
	if err != nil {
		return err
	}

	err = gobtools.DecodeStruct(buf, &r.implicitDeps)
	if err != nil {
		return err
	}

	err = gobtools.DecodeStruct(buf, &r.orderOnlyDeps)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.executable)
	if err != nil {
		return err
	}

	var isNil14 bool
	if err = gobtools.DecodeSimple(buf, &isNil14); err != nil {
		return err
	}
	if !isNil14 {
		var val14 extraFilesZip
		err = gobtools.DecodeStruct(buf, &val14)
		if err != nil {
			return err
		}
		r.extraFiles = &val14
	}

	err = gobtools.DecodeString(buf, &r.absFrom)
	if err != nil {
		return err
	}

	return nil
}

func (r extraFilesZip) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	var err error

	if err = gobtools.EncodeStruct(buf, &r.zip); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeStruct(buf, &r.dir); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r *extraFilesZip) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	err := r.Decode(buf)
	return err
}

func (r *extraFilesZip) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeStruct(buf, &r.zip)
	if err != nil {
		return err
	}

	err = gobtools.DecodeStruct(buf, &r.dir)
	if err != nil {
		return err
	}

	return nil
}
