// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func (r katiInstall) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	if err := r.Encode(buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r katiInstall) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(buf, &r.from); err != nil {
		return err
	}

	if err = gobtools.EncodeStruct(buf, &r.to); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.implicitDeps))); err != nil {
		return err
	}
	for val1 := 0; val1 < len(r.implicitDeps); val1++ {
		if err = gobtools.EncodeInterface(buf, &r.implicitDeps[val1]); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, int32(len(r.orderOnlyDeps))); err != nil {
		return err
	}
	for val2 := 0; val2 < len(r.orderOnlyDeps); val2++ {
		if err = gobtools.EncodeInterface(buf, &r.orderOnlyDeps[val2]); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeSimple(buf, r.executable); err != nil {
		return err
	}

	val3 := r.extraFiles == nil
	if err = gobtools.EncodeSimple(buf, val3); err != nil {
		return err
	}
	if !val3 {
		if err = gobtools.EncodeStruct(buf, &*r.extraFiles); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeString(buf, r.absFrom); err != nil {
		return err
	}
	return nil
}

func (r *katiInstall) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	return r.Decode(buf)
}

func (r *katiInstall) Decode(buf *bytes.Reader) error {
	var err error

	if err = gobtools.DecodeInterface(buf, &r.from); err != nil {
		return err
	}

	if err = gobtools.DecodeStruct(buf, &r.to); err != nil {
		return err
	}

	var val5 int32
	err = gobtools.DecodeSimple[int32](buf, &val5)
	if err != nil {
		return err
	}
	if val5 > 0 {
		r.implicitDeps = make([]Path, val5)
		for val6 := 0; val6 < int(val5); val6++ {
			if err = gobtools.DecodeInterface(buf, &r.implicitDeps[val6]); err != nil {
				return err
			}
		}
	}

	var val10 int32
	err = gobtools.DecodeSimple[int32](buf, &val10)
	if err != nil {
		return err
	}
	if val10 > 0 {
		r.orderOnlyDeps = make([]Path, val10)
		for val11 := 0; val11 < int(val10); val11++ {
			if err = gobtools.DecodeInterface(buf, &r.orderOnlyDeps[val11]); err != nil {
				return err
			}
		}
	}

	err = gobtools.DecodeSimple[bool](buf, &r.executable)
	if err != nil {
		return err
	}

	var val15 bool
	if err = gobtools.DecodeSimple(buf, &val15); err != nil {
		return err
	}
	if !val15 {
		var val14 extraFilesZip
		if err = gobtools.DecodeStruct(buf, &val14); err != nil {
			return err
		}
		r.extraFiles = &val14
	}

	err = gobtools.DecodeString(buf, &r.absFrom)
	if err != nil {
		return err
	}

	return nil
}

func (r extraFilesZip) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	if err := r.Encode(buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r extraFilesZip) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(buf, &r.zip); err != nil {
		return err
	}

	if err = gobtools.EncodeStruct(buf, &r.dir); err != nil {
		return err
	}
	return nil
}

func (r *extraFilesZip) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	return r.Decode(buf)
}

func (r *extraFilesZip) Decode(buf *bytes.Reader) error {
	var err error

	if err = gobtools.DecodeInterface(buf, &r.zip); err != nil {
		return err
	}

	if err = gobtools.DecodeStruct(buf, &r.dir); err != nil {
		return err
	}

	return nil
}
