// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
	"github.com/google/blueprint/uniquelist"
)

func (r PackagingSpec) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	var err error

	if err = gobtools.EncodeString(buf, r.relPathInPackage); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeStruct(buf, &r.srcPath); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeString(buf, r.symlinkTarget); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, r.executable); err != nil {
		return nil, err
	}

	unilst5 := r.effectiveLicenseFiles.ToSlice()
	if err = gobtools.EncodeSimple(buf, int32(len(unilst5))); err != nil {
		return nil, err
	}
	for i := 0; i < len(unilst5); i++ {
		if err = gobtools.EncodeStruct(buf, &unilst5[i]); err != nil {
			return nil, err
		}
	}

	if err = gobtools.EncodeString(buf, r.partition); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, r.skipInstall); err != nil {
		return nil, err
	}

	unilst9 := r.aconfigPaths.ToSlice()
	if err = gobtools.EncodeSimple(buf, int32(len(unilst9))); err != nil {
		return nil, err
	}
	for i := 0; i < len(unilst9); i++ {
		if err = gobtools.EncodeStruct(buf, &unilst9[i]); err != nil {
			return nil, err
		}
	}

	if err = gobtools.EncodeStruct(buf, &r.archType); err != nil {
		return nil, err
	}

	unilst12 := r.overrides.ToSlice()
	if err = gobtools.EncodeSimple(buf, int32(len(unilst12))); err != nil {
		return nil, err
	}
	for i := 0; i < len(unilst12); i++ {
		if err = gobtools.EncodeString(buf, unilst12[i]); err != nil {
			return nil, err
		}
	}

	if err = gobtools.EncodeString(buf, r.owner); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, r.requiresFullInstall); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeStruct(buf, &r.fullInstallPath); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeString(buf, r.variation); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, r.prebuilt); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r *PackagingSpec) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	err := r.Decode(buf)
	return err
}

func (r *PackagingSpec) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.relPathInPackage)
	if err != nil {
		return err
	}

	err = gobtools.DecodeStruct(buf, &r.srcPath)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.symlinkTarget)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.executable)
	if err != nil {
		return err
	}

	var unilst23 []Path
	var val23 int32
	err = gobtools.DecodeSimple[int32](buf, &val23)
	if err != nil {
		return err
	}
	if val23 > 0 {
		unilst23 = make([]Path, val23)
		for i := 0; i < int(val23); i++ {
			err = gobtools.DecodeStruct(buf, &unilst23[i])
			if err != nil {
				return err
			}
		}
	}
	r.effectiveLicenseFiles = uniquelist.Make(unilst23)

	err = gobtools.DecodeString(buf, &r.partition)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.skipInstall)
	if err != nil {
		return err
	}

	var unilst27 []Path
	var val27 int32
	err = gobtools.DecodeSimple[int32](buf, &val27)
	if err != nil {
		return err
	}
	if val27 > 0 {
		unilst27 = make([]Path, val27)
		for i := 0; i < int(val27); i++ {
			err = gobtools.DecodeStruct(buf, &unilst27[i])
			if err != nil {
				return err
			}
		}
	}
	r.aconfigPaths = uniquelist.Make(unilst27)

	err = gobtools.DecodeStruct(buf, &r.archType)
	if err != nil {
		return err
	}

	var unilst30 []string
	var val30 int32
	err = gobtools.DecodeSimple[int32](buf, &val30)
	if err != nil {
		return err
	}
	if val30 > 0 {
		unilst30 = make([]string, val30)
		for i := 0; i < int(val30); i++ {
			err = gobtools.DecodeString(buf, &unilst30[i])
			if err != nil {
				return err
			}
		}
	}
	r.overrides = uniquelist.Make(unilst30)

	err = gobtools.DecodeString(buf, &r.owner)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.requiresFullInstall)
	if err != nil {
		return err
	}

	err = gobtools.DecodeStruct(buf, &r.fullInstallPath)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.variation)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.prebuilt)
	if err != nil {
		return err
	}

	return nil
}
