// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
	"github.com/google/blueprint/uniquelist"
)

func (r PackagingSpec) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	if err := r.Encode(buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r PackagingSpec) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.relPathInPackage); err != nil {
		return err
	}

	if err = gobtools.EncodeInterface(buf, &r.srcPath); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.symlinkTarget); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.executable); err != nil {
		return err
	}

	val1 := r.effectiveLicenseFiles.ToSlice()
	if err = gobtools.EncodeSimple(buf, int32(len(val1))); err != nil {
		return err
	}
	for val2 := 0; val2 < len(val1); val2++ {
		if err = gobtools.EncodeInterface(buf, &val1[val2]); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeString(buf, r.partition); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.skipInstall); err != nil {
		return err
	}

	val3 := r.aconfigPaths.ToSlice()
	if err = gobtools.EncodeSimple(buf, int32(len(val3))); err != nil {
		return err
	}
	for val4 := 0; val4 < len(val3); val4++ {
		if err = gobtools.EncodeInterface(buf, &val3[val4]); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeStruct(buf, &r.archType); err != nil {
		return err
	}

	val5 := r.overrides.ToSlice()
	if err = gobtools.EncodeSimple(buf, int32(len(val5))); err != nil {
		return err
	}
	for val6 := 0; val6 < len(val5); val6++ {
		if err = gobtools.EncodeString(buf, val5[val6]); err != nil {
			return err
		}
	}

	if err = gobtools.EncodeString(buf, r.owner); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.requiresFullInstall); err != nil {
		return err
	}

	if err = gobtools.EncodeStruct(buf, &r.fullInstallPath); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.variation); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.prebuilt); err != nil {
		return err
	}
	return nil
}

func (r *PackagingSpec) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	return r.Decode(buf)
}

func (r *PackagingSpec) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.relPathInPackage)
	if err != nil {
		return err
	}

	if err = gobtools.DecodeInterface(buf, &r.srcPath); err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.symlinkTarget)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.executable)
	if err != nil {
		return err
	}

	var val6 []Path
	var val7 int32
	err = gobtools.DecodeSimple[int32](buf, &val7)
	if err != nil {
		return err
	}
	if val7 > 0 {
		val6 = make([]Path, val7)
		for val8 := 0; val8 < int(val7); val8++ {
			if err = gobtools.DecodeInterface(buf, &val6[val8]); err != nil {
				return err
			}
		}
	}
	r.effectiveLicenseFiles = uniquelist.Make(val6)

	err = gobtools.DecodeString(buf, &r.partition)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.skipInstall)
	if err != nil {
		return err
	}

	var val13 []Path
	var val14 int32
	err = gobtools.DecodeSimple[int32](buf, &val14)
	if err != nil {
		return err
	}
	if val14 > 0 {
		val13 = make([]Path, val14)
		for val15 := 0; val15 < int(val14); val15++ {
			if err = gobtools.DecodeInterface(buf, &val13[val15]); err != nil {
				return err
			}
		}
	}
	r.aconfigPaths = uniquelist.Make(val13)

	if err = gobtools.DecodeStruct(buf, &r.archType); err != nil {
		return err
	}

	var val19 []string
	var val20 int32
	err = gobtools.DecodeSimple[int32](buf, &val20)
	if err != nil {
		return err
	}
	if val20 > 0 {
		val19 = make([]string, val20)
		for val21 := 0; val21 < int(val20); val21++ {
			err = gobtools.DecodeString(buf, &val19[val21])
			if err != nil {
				return err
			}
		}
	}
	r.overrides = uniquelist.Make(val19)

	err = gobtools.DecodeString(buf, &r.owner)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.requiresFullInstall)
	if err != nil {
		return err
	}

	if err = gobtools.DecodeStruct(buf, &r.fullInstallPath); err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.variation)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.prebuilt)
	if err != nil {
		return err
	}

	return nil
}
