// Code generated by go run gob_gen.go -source paths.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func (r basePath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	var err error

	if err = gobtools.EncodeString(buf, r.path); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeString(buf, r.rel); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r *basePath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	err := r.Decode(buf)
	return err
}

func (r *basePath) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.path)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.rel)
	if err != nil {
		return err
	}

	return nil
}

func (r SourcePath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	var err error

	if err = gobtools.EncodeStruct(buf, &r.basePath); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r *SourcePath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	err := r.Decode(buf)
	return err
}

func (r *SourcePath) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeStruct(buf, &r.basePath)
	if err != nil {
		return err
	}

	return nil
}

func (r OutputPath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	var err error

	if err = gobtools.EncodeStruct(buf, &r.basePath); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeString(buf, r.outDir); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeString(buf, r.fullPath); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r *OutputPath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	err := r.Decode(buf)
	return err
}

func (r *OutputPath) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeStruct(buf, &r.basePath)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.outDir)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.fullPath)
	if err != nil {
		return err
	}

	return nil
}

func (r toolDepPath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	var err error

	if err = gobtools.EncodeStruct(buf, &r.basePath); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r *toolDepPath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	err := r.Decode(buf)
	return err
}

func (r *toolDepPath) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeStruct(buf, &r.basePath)
	if err != nil {
		return err
	}

	return nil
}

func (r ModuleOutPath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	var err error

	if err = gobtools.EncodeStruct(buf, &r.OutputPath); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r *ModuleOutPath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	err := r.Decode(buf)
	return err
}

func (r *ModuleOutPath) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeStruct(buf, &r.OutputPath)
	if err != nil {
		return err
	}

	return nil
}

func (r ModuleGenPath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	var err error

	if err = gobtools.EncodeStruct(buf, &r.ModuleOutPath); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r *ModuleGenPath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	err := r.Decode(buf)
	return err
}

func (r *ModuleGenPath) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeStruct(buf, &r.ModuleOutPath)
	if err != nil {
		return err
	}

	return nil
}

func (r ModuleObjPath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	var err error

	if err = gobtools.EncodeStruct(buf, &r.ModuleOutPath); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r *ModuleObjPath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	err := r.Decode(buf)
	return err
}

func (r *ModuleObjPath) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeStruct(buf, &r.ModuleOutPath)
	if err != nil {
		return err
	}

	return nil
}

func (r ModuleResPath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	var err error

	if err = gobtools.EncodeStruct(buf, &r.ModuleOutPath); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r *ModuleResPath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	err := r.Decode(buf)
	return err
}

func (r *ModuleResPath) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeStruct(buf, &r.ModuleOutPath)
	if err != nil {
		return err
	}

	return nil
}

func (r InstallPath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	var err error

	if err = gobtools.EncodeStruct(buf, &r.basePath); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeString(buf, r.soongOutDir); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeString(buf, r.partitionDir); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeString(buf, r.partition); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, r.makePath); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeString(buf, r.fullPath); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r *InstallPath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	err := r.Decode(buf)
	return err
}

func (r *InstallPath) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeStruct(buf, &r.basePath)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.soongOutDir)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.partitionDir)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.partition)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.makePath)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.fullPath)
	if err != nil {
		return err
	}

	return nil
}

func (r PhonyPath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	var err error

	if err = gobtools.EncodeStruct(buf, &r.basePath); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r *PhonyPath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	err := r.Decode(buf)
	return err
}

func (r *PhonyPath) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeStruct(buf, &r.basePath)
	if err != nil {
		return err
	}

	return nil
}

func (r testPath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	var err error

	if err = gobtools.EncodeStruct(buf, &r.basePath); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r *testPath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	err := r.Decode(buf)
	return err
}

func (r *testPath) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeStruct(buf, &r.basePath)
	if err != nil {
		return err
	}

	return nil
}

func (r DataPath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	var err error

	if err = gobtools.EncodeStruct(buf, &r.SrcPath); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeString(buf, r.RelativeInstallPath); err != nil {
		return nil, err
	}

	if err = gobtools.EncodeSimple(buf, r.WithoutRel); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r *DataPath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	err := r.Decode(buf)
	return err
}

func (r *DataPath) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeStruct(buf, &r.SrcPath)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.RelativeInstallPath)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.WithoutRel)
	if err != nil {
		return err
	}

	return nil
}
