// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	basePathGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(basePath) })
	SourcePathGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SourcePath) })
	OutputPathGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(OutputPath) })
	toolDepPathGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(toolDepPath) })
	ModuleOutPathGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ModuleOutPath) })
	ModuleGenPathGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ModuleGenPath) })
	ModuleObjPathGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ModuleObjPath) })
	ModuleResPathGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(ModuleResPath) })
	InstallPathGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(InstallPath) })
	PhonyPathGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(PhonyPath) })
	testPathGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(testPath) })
	DataPathGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(DataPath) })
}

func (r basePath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	if err := r.Encode(buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r basePath) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeString(buf, r.path); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.rel); err != nil {
		return err
	}
	return nil
}

func (r *basePath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	return r.Decode(buf)
}

func (r *basePath) Decode(buf *bytes.Reader) error {
	var err error

	err = gobtools.DecodeString(buf, &r.path)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.rel)
	if err != nil {
		return err
	}

	return nil
}

var basePathGobRegId int16

func (r basePath) GetTypeId() int16 {
	return basePathGobRegId
}

func (r SourcePath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	if err := r.Encode(buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r SourcePath) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeStruct(buf, &r.basePath); err != nil {
		return err
	}
	return nil
}

func (r *SourcePath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	return r.Decode(buf)
}

func (r *SourcePath) Decode(buf *bytes.Reader) error {
	var err error

	if err = gobtools.DecodeStruct(buf, &r.basePath); err != nil {
		return err
	}

	return nil
}

var SourcePathGobRegId int16

func (r SourcePath) GetTypeId() int16 {
	return SourcePathGobRegId
}

func (r OutputPath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	if err := r.Encode(buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r OutputPath) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeStruct(buf, &r.basePath); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.outDir); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.fullPath); err != nil {
		return err
	}
	return nil
}

func (r *OutputPath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	return r.Decode(buf)
}

func (r *OutputPath) Decode(buf *bytes.Reader) error {
	var err error

	if err = gobtools.DecodeStruct(buf, &r.basePath); err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.outDir)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.fullPath)
	if err != nil {
		return err
	}

	return nil
}

var OutputPathGobRegId int16

func (r OutputPath) GetTypeId() int16 {
	return OutputPathGobRegId
}

func (r toolDepPath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	if err := r.Encode(buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r toolDepPath) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeStruct(buf, &r.basePath); err != nil {
		return err
	}
	return nil
}

func (r *toolDepPath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	return r.Decode(buf)
}

func (r *toolDepPath) Decode(buf *bytes.Reader) error {
	var err error

	if err = gobtools.DecodeStruct(buf, &r.basePath); err != nil {
		return err
	}

	return nil
}

var toolDepPathGobRegId int16

func (r toolDepPath) GetTypeId() int16 {
	return toolDepPathGobRegId
}

func (r ModuleOutPath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	if err := r.Encode(buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r ModuleOutPath) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeStruct(buf, &r.OutputPath); err != nil {
		return err
	}
	return nil
}

func (r *ModuleOutPath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	return r.Decode(buf)
}

func (r *ModuleOutPath) Decode(buf *bytes.Reader) error {
	var err error

	if err = gobtools.DecodeStruct(buf, &r.OutputPath); err != nil {
		return err
	}

	return nil
}

var ModuleOutPathGobRegId int16

func (r ModuleOutPath) GetTypeId() int16 {
	return ModuleOutPathGobRegId
}

func (r ModuleGenPath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	if err := r.Encode(buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r ModuleGenPath) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeStruct(buf, &r.ModuleOutPath); err != nil {
		return err
	}
	return nil
}

func (r *ModuleGenPath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	return r.Decode(buf)
}

func (r *ModuleGenPath) Decode(buf *bytes.Reader) error {
	var err error

	if err = gobtools.DecodeStruct(buf, &r.ModuleOutPath); err != nil {
		return err
	}

	return nil
}

var ModuleGenPathGobRegId int16

func (r ModuleGenPath) GetTypeId() int16 {
	return ModuleGenPathGobRegId
}

func (r ModuleObjPath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	if err := r.Encode(buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r ModuleObjPath) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeStruct(buf, &r.ModuleOutPath); err != nil {
		return err
	}
	return nil
}

func (r *ModuleObjPath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	return r.Decode(buf)
}

func (r *ModuleObjPath) Decode(buf *bytes.Reader) error {
	var err error

	if err = gobtools.DecodeStruct(buf, &r.ModuleOutPath); err != nil {
		return err
	}

	return nil
}

var ModuleObjPathGobRegId int16

func (r ModuleObjPath) GetTypeId() int16 {
	return ModuleObjPathGobRegId
}

func (r ModuleResPath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	if err := r.Encode(buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r ModuleResPath) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeStruct(buf, &r.ModuleOutPath); err != nil {
		return err
	}
	return nil
}

func (r *ModuleResPath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	return r.Decode(buf)
}

func (r *ModuleResPath) Decode(buf *bytes.Reader) error {
	var err error

	if err = gobtools.DecodeStruct(buf, &r.ModuleOutPath); err != nil {
		return err
	}

	return nil
}

var ModuleResPathGobRegId int16

func (r ModuleResPath) GetTypeId() int16 {
	return ModuleResPathGobRegId
}

func (r InstallPath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	if err := r.Encode(buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r InstallPath) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeStruct(buf, &r.basePath); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.soongOutDir); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.partitionDir); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.partition); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.makePath); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.fullPath); err != nil {
		return err
	}
	return nil
}

func (r *InstallPath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	return r.Decode(buf)
}

func (r *InstallPath) Decode(buf *bytes.Reader) error {
	var err error

	if err = gobtools.DecodeStruct(buf, &r.basePath); err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.soongOutDir)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.partitionDir)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.partition)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.makePath)
	if err != nil {
		return err
	}

	err = gobtools.DecodeString(buf, &r.fullPath)
	if err != nil {
		return err
	}

	return nil
}

var InstallPathGobRegId int16

func (r InstallPath) GetTypeId() int16 {
	return InstallPathGobRegId
}

func (r PhonyPath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	if err := r.Encode(buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r PhonyPath) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeStruct(buf, &r.basePath); err != nil {
		return err
	}
	return nil
}

func (r *PhonyPath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	return r.Decode(buf)
}

func (r *PhonyPath) Decode(buf *bytes.Reader) error {
	var err error

	if err = gobtools.DecodeStruct(buf, &r.basePath); err != nil {
		return err
	}

	return nil
}

var PhonyPathGobRegId int16

func (r PhonyPath) GetTypeId() int16 {
	return PhonyPathGobRegId
}

func (r testPath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	if err := r.Encode(buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r testPath) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeStruct(buf, &r.basePath); err != nil {
		return err
	}
	return nil
}

func (r *testPath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	return r.Decode(buf)
}

func (r *testPath) Decode(buf *bytes.Reader) error {
	var err error

	if err = gobtools.DecodeStruct(buf, &r.basePath); err != nil {
		return err
	}

	return nil
}

var testPathGobRegId int16

func (r testPath) GetTypeId() int16 {
	return testPathGobRegId
}

func (r DataPath) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	if err := r.Encode(buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r DataPath) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(buf, r.SrcPath); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.RelativeInstallPath); err != nil {
		return err
	}

	if err = gobtools.EncodeSimple(buf, r.WithoutRel); err != nil {
		return err
	}
	return nil
}

func (r *DataPath) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	return r.Decode(buf)
}

func (r *DataPath) Decode(buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(buf); err != nil {
		return err
	} else if val2 == nil {
		r.SrcPath = nil
	} else {
		r.SrcPath = val2.(Path)
	}

	err = gobtools.DecodeString(buf, &r.RelativeInstallPath)
	if err != nil {
		return err
	}

	err = gobtools.DecodeSimple[bool](buf, &r.WithoutRel)
	if err != nil {
		return err
	}

	return nil
}

var DataPathGobRegId int16

func (r DataPath) GetTypeId() int16 {
	return DataPathGobRegId
}
