// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	RuleBuilderInstallGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(RuleBuilderInstall) })
}

func (r RuleBuilderInstall) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	if err := r.Encode(buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r RuleBuilderInstall) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(buf, r.From); err != nil {
		return err
	}

	if err = gobtools.EncodeString(buf, r.To); err != nil {
		return err
	}
	return err
}

func (r *RuleBuilderInstall) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	return r.Decode(buf)
}

func (r *RuleBuilderInstall) Decode(buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(buf); err != nil {
		return err
	} else if val2 == nil {
		r.From = nil
	} else {
		r.From = val2.(Path)
	}

	err = gobtools.DecodeString(buf, &r.To)
	if err != nil {
		return err
	}

	return err
}

var RuleBuilderInstallGobRegId int16

func (r RuleBuilderInstall) GetTypeId() int16 {
	return RuleBuilderInstallGobRegId
}
