// Code generated by go run gob_gen.go; DO NOT EDIT.

package android

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	SymbolicOutputInfoGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(SymbolicOutputInfo) })
}

func (r SymbolicOutputInfo) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	if err := r.Encode(buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r SymbolicOutputInfo) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeInterface(buf, r.UnstrippedOutputFile); err != nil {
		return err
	}

	if err = r.SymbolicOutputPath.Encode(buf); err != nil {
		return err
	}

	if err = r.ElfMappingProtoPath.Encode(buf); err != nil {
		return err
	}
	return err
}

func (r *SymbolicOutputInfo) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	return r.Decode(buf)
}

func (r *SymbolicOutputInfo) Decode(buf *bytes.Reader) error {
	var err error

	if val2, err := gobtools.DecodeInterface(buf); err != nil {
		return err
	} else if val2 == nil {
		r.UnstrippedOutputFile = nil
	} else {
		r.UnstrippedOutputFile = val2.(Path)
	}

	if err = r.SymbolicOutputPath.Decode(buf); err != nil {
		return err
	}

	if err = r.ElfMappingProtoPath.Decode(buf); err != nil {
		return err
	}

	return err
}

var SymbolicOutputInfoGobRegId int16

func (r SymbolicOutputInfo) GetTypeId() int16 {
	return SymbolicOutputInfoGobRegId
}
