// Code generated by go run gob_gen.go; DO NOT EDIT.

package cc

import (
	"bytes"
	"github.com/google/blueprint/gobtools"
)

func init() {
	binarySdkMemberTypeGobRegId = gobtools.RegisterType(func() gobtools.CustomDec { return new(binarySdkMemberType) })
}

func (r binarySdkMemberType) GobEncode() ([]byte, error) {
	buf := new(bytes.Buffer)

	if err := r.Encode(buf); err != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

func (r binarySdkMemberType) Encode(buf *bytes.Buffer) error {
	var err error

	if err = gobtools.EncodeStruct(buf, &r.SdkMemberTypeBase); err != nil {
		return err
	}
	return nil
}

func (r *binarySdkMemberType) GobDecode(b []byte) error {
	buf := bytes.NewReader(b)
	return r.Decode(buf)
}

func (r *binarySdkMemberType) Decode(buf *bytes.Reader) error {
	var err error

	if err = gobtools.DecodeStruct(buf, &r.SdkMemberTypeBase); err != nil {
		return err
	}

	return nil
}

var binarySdkMemberTypeGobRegId int16

func (r binarySdkMemberType) GetTypeId() int16 {
	return binarySdkMemberTypeGobRegId
}
